<?php

declare(strict_types=1);

namespace Sabatier\Foundation\Predicates;

use function Sabatier\Foundation\fatal_error;

/** @internal */
enum ExpressionOperatorType: int
{
    case average = 0;
    case sum = 1;
    case count = 2;
    case min = 3;
    case max = 4;
    case median = 5;
    case mode = 6;
    case stddev = 7;
    case addTo = 10;
    case fromSubtract = 11;
    case multiplyBy = 12;
    case divideBy = 13;
    case modulusBy = 14;
    case sqrt = 20;
    case ln = 21;
    case log = 22;
    case raiseToPower = 23;
    case exp = 24;
    case ceiling = 25;
    case abs = 26;
    case trunc = 27;
    case floor = 28;
    case round = 29;
    case random = 30;
    case chs = 31;
    case bitwiseAndWith = 40;
    case bitwiseOrWith = 41;
    case bitwiseXorWith = 42;
    case leftshiftBy = 43;
    case rightshiftBy = 44;
    case onesComplement = 45;
    case now = 100;
    case currentDate = 101;
    case date = 102;
    case year = 103;
    case month = 104;
    case week = 105;
    case day = 106;
    case hour = 107;
    case minute = 108;
    case second = 109;
    case dateFormat = 110;
    case dateDiff = 111;
    case dateAdd = 112;
    case dateSub = 113;
    case quarter = 114;
    case lastDay = 115;
    case dayOfWeek = 116;
    case dayOfYear = 117;
    case fromUnixTime = 118;
    case unixTimestamp = 119;
    case addTime = 120;
    case subTime = 121;
    case uppercase = 200;
    case lowercase = 201;
    case canonical = 202;
    case concat = 203;
    case substring = 204;
    case replace = 205;
    case regexpReplace = 206;
    case length = 207;
    case trim = 208;
    case lpad = 209;
    case rpad = 210;
    case left = 211;
    case right = 212;
    case instr = 213;
    case reverse = 214;
    case repeat = 215;
    case index = 300;
    case indexFirst = 301;
    case indexLast = 302;
    case indexSize = 303;
    case isNull = 400;
    case ifNull = 401;
    case nullIf = 402;
    case coalesce = 403;
    case greatest = 404;
    case least = 405;
    case uuid = 500;
    case cast = 501;

    public static function fromFunctionName(string $functionName): ExpressionOperatorType
    {
        return match ($functionName) {
            "average:", "avg:" => self::average,
            "sum:" => self::sum,
            "count:" => self::count,
            "min:" => self::min,
            "max:" => self::max,
            "median:" => self::median,
            "mode:" => self::mode,
            "stddev:" => self::stddev,
            "add:to:" => self::addTo,
            "from:subtract:" => self::fromSubtract,
            "multiply:by:" => self::multiplyBy,
            "divide:by:" => self::divideBy,
            "modulus:by:" => self::modulusBy,
            "sqrt:" => self::sqrt,
            "ln:" => self::ln,
            "log:" => self::log,
            "raise:toPower:" => self::raiseToPower,
            "exp:" => self::exp,
            "ceiling:", "ceil:" => self::ceiling,
            "abs:" => self::abs,
            "trunc:" => self::trunc,
            "floor:" => self::floor,
            "round:" => self::round,
            "random:" => self::random,
            "chs:" => self::chs,
            "bitwiseAnd:with:" => self::bitwiseAndWith,
            "bitwiseOr:with:" => self::bitwiseOrWith,
            "bitwiseXor:with:" => self::bitwiseXorWith,
            "leftshift:by:" => self::leftshiftBy,
            "rightshift:by:" => self::rightshiftBy,
            "onesComplement:" => self::onesComplement,
            "now:" => self::now,
            "curdate:" => self::currentDate,
            "date:" => self::date,
            "year:" => self::year,
            "month:" => self::month,
            "day:" => self::day,
            "hour:" => self::hour,
            "minute:" => self::minute,
            "second:" => self::second,
            "week:" => self::week,
            "quarter:" => self::quarter,
            "dayofweek:" => self::dayOfWeek,
            "dayofyear:" => self::dayOfYear,
            "lastday:" => self::lastDay,
            "date:format:" => self::dateFormat,
            "datediff:" => self::dateDiff,
            "dateadd:" => self::dateAdd,
            "datesub:" => self::dateSub,
            "addtime:" => self::addTime,
            "subtime:" => self::subTime,
            "fromunixtime:" => self::fromUnixTime,
            "unixtimestamp:" => self::unixTimestamp,
            "uppercase:" => self::uppercase,
            "lowercase:" => self::lowercase,
            "canonical:" => self::canonical,
            "concat:" => self::concat,
            "substring:" => self::substring,
            "replace:" => self::replace,
            "regexpReplace:" => self::regexpReplace,
            "length:" => self::length,
            "trim:" => self::trim,
            "lpad:" => self::lpad,
            "rpad:" => self::rpad,
            "left:" => self::left,
            "right:" => self::right,
            "instr:" => self::instr,
            "reverse:" => self::reverse,
            "repeat:" => self::repeat,
            "index:" => self::index,
            "first:" => self::indexFirst,
            "last:" => self::indexLast,
            "size:" => self::indexSize,
            "isNull:" => self::isNull,
            "ifNull:" => self::ifNull,
            "nullIf:" => self::nullIf,
            "coalesce:" => self::coalesce,
            "greatest:" => self::greatest,
            "least:" => self::least,
            "uuid:" => self::uuid,
            "cast:" => self::cast,
            default => fatal_error(sprintf("%s unable to parse selector name \"%s\" into supported method", self::class, $functionName))
        };
    }
}
